services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: pilotgb
      POSTGRES_PASSWORD: pilotgb
      POSTGRES_DB: pilotgb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
